### ISSUE TITLE
onClose() does not work if supplying a URL

### ISSUE THREAD

**Issue by don1989** [ticlo/rc-new-window#2]
Previously I was using react-new-window to handle our windowing features.

In that library, you can use onUnload() to handle any cleanup when you close the new window that has just popped up. This works.

```
<NewWindow 
            url='upload'
            name='upload'
            title='title'
            features={{ width: 1200, height: 600 }}
            onUnload={()=>{ console.log('OnUnload'); }} />
```

However when using rc-new-window, the equivalent onClose(), does not get called when you supply a URL, however it IS called when you don't give a URL.

```
<NewWindow 
            url='upload'
            name='upload'
            title='title'
            width={1200}
            height={600}
            onClose={()=>{ console.log('onClose'); }} /> // OnClose won't actually get called when a url is given.
```

```
<NewWindow 
            name='upload'
            title='title'
            width={1200}
            height={600}
            onClose={()=>{ console.log('onClose'); }} /> // OnClose will get called when a url is not given, but will display about:blank.
```

**Comment by rinick** [comment]
@don1989 when url is defined, you will need to add a listener inside the popup. because the parent window is not able to listen to that event.

please check this link for a work around
https://stackoverflow.com/questions/3291712/is-it-possible-to-open-a-popup-with-javascript-and-then-detect-when-the-user-clo

However, if your popup page allows iframe, and you don't mind showing about:blank in the adress bar. you can simply use iframe instead of the url property

**Comment by don1989** [comment]
Thanks @rinick 
The reason why we use the URL is so that we can hide the about:blank in the address bar. 

It looks like the workaround that you linked was in some form originally in react-new-window.

```
// When a new window use content from a cross-origin there's no way we can attach event
// to it. Therefore, we need to detect in a interval when the new window was destroyed
// or was closed.
this.windowCheckerInterval = setInterval(() => {
  if (!this.window || this.window.closed) {
    this.release()
  }
}, 50)
```

Is it possible to get this within rc-new-window so onClose works?

**Comment by rinick** [comment]
> Thanks @rinick
> The reason why we use the URL is so that we can hide the about:blank in the address bar.
> 
> It looks like the workaround that you linked was in some form originally in react-new-window.
> 
> ```
> // When a new window use content from a cross-origin there's no way we can attach event
> // to it. Therefore, we need to detect in a interval when the new window was destroyed
> // or was closed.
> this.windowCheckerInterval = setInterval(() => {
>   if (!this.window || this.window.closed) {
>     this.release()
>   }
> }, 50)
> ```
> 
> Is it possible to get this within rc-new-window so onClose works?

Ok, I will add that

**Comment by rinick** [comment]
@don1989  please check version 0.1.8

**Comment by don1989** [comment]
That works, thanks!
