### ISSUE TITLE
Initial window position not correct on secondary screen.

### ISSUE THREAD

**Issue by don1989** [ticlo/rc-new-window#3]
When going through any of the demos on a secondary monitor, the popped out window seems to be cut off to the top-left and positioned incorrectly relative to the parent window.

If I run the demo on my main monitor, the window positions are correct.

There's probably some workarounds I can do using the innerRect functions, however I wanted to see if this can be working out of the box. Here is a link that may shed some light on the issue: https://stackoverflow.com/questions/16363474/window-open-on-a-multi-monitor-dual-monitor-system-where-does-window-pop-up

**Comment by rinick** [comment]
which OS are you using?
I tested that on windows and it seems to work fine

**Comment by don1989** [comment]
I'm also using windows and tested with Google Chrome and MS Edge

**Comment by don1989** [comment]
These are my display settings if it helps.

![image](https://user-images.githubusercontent.com/10096212/116278489-71174380-a77e-11eb-9aa9-026718d499b6.png)

**Comment by rinick** [comment]
@don1989  are they 2 monitors with different scale level?  seems I can only reproduce with this usecase

also I can only reproduce this issue in Chrome, but not in firefox, so I think it's more like Google's bug.

Maybe related to this:
https://bugs.chromium.org/p/chromium/issues/detail?id=778141
