### ISSUE TITLE
TypeError: browser.getBrowserName is not a function

### ISSUE THREAD

**Issue by chris-kruining** [ticlo/rc-new-window#4]
I just installed the docklayout component package and tried to run the hello world set up. But I encountered this error. any clue as what I might be doing wrong?

I am running a remix app which does server side rendering, might that be the issue?

**Comment by chris-kruining** [comment]
I see that the docklayout itself relies on `window`. so this issue is bigger I think.

Any advice on this? I love both remix and your docklayout.

**Comment by rinick** [comment]
I'm really confused, you mean a library that opens and closes window should not rely on window?

**Comment by rinick** [comment]
is it related to unit test with jsdom?

**Comment by chris-kruining** [comment]
this issue is caused by the server rendering of remix. I have managed to do client rendering only for the dock component, so the issue is resolved for me. therefor as far as I am concerned this issue may closed. I would suggest to not rely on any browser api and either polyfill it or allow for a workaround, somehow. For the folks that might wanna run this in node with -as you suggested- unit tetsting. I do agree that asking a window opening lib not to rely on window is weird. but my use case was caused because this lib is a dependency of another, so I think that such cases might be worth looking into. again, all this is a mere suggestion, I do not want to make a you-should-do-this statement. :D

**Comment by rinick** [comment]
Could you update to 0,1,13 and see if this bug is fixed?

**Comment by chris-kruining** [comment]
wouldn't updating be an issue for rc-dock? because I am using that lib, this lib is just the dependency of that one

**Comment by chris-kruining** [comment]
this seems to fix the issue, I quickly applied your patch manually to the lib file in node_modules. I still came across an issue with rc-docks itself, I'll create a PR for that fix
